### ISSUE TITLE
Rest countdown timer sometimes shows ":60" and ":010" in the seconds field.

### ISSUE THREAD

**Issue by moyamo** [Qazzquimby/third-time#2]
I've noticed that the break countdown timer shows weird numbers like "12:010" and "12:60" instead of "12:10" and "13:00"

I think the problem is this code:

## :010

```

export function formatTime(inputSeconds: number): string {
  const duration = Duration.fromMillis(inputSeconds * 1000)
  let { hours = 0, minutes = 0, seconds = 0 } = duration.shiftTo('hours', 'minutes', 'seconds').toObject()

  hours = Math.abs(hours)
  minutes = Math.abs(minutes)
  seconds = Math.abs(seconds)

  const minusSign = duration.milliseconds < 0 ? '-' : ''
  const hoursString = hours ? `${hours}:` : ''
  const minutesString = `${minutes !== undefined && minutes < 10 ? '0' : ''}${minutes}:`
  const secondsString = `${seconds !== undefined && seconds < 10 ? '0' : ''}${seconds.toFixed(0)}`

  return `${minusSign}${hoursString}${minutesString}${secondsString}`
}
```

Consider

```
  const secondsString = `${seconds !== undefined && seconds < 10 ? '0' : ''}${seconds.toFixed(0)}`
```

if `seconds = 9.9` then `seconds < 10` but `seconds.toFixed(0) == 10`

Rounding off earlier would help fix this bug properly

## :60

Consider `minutes = 12` and `seconds = 59.9`.  I think you need to do something like 

```
if(seconds.toFixed(0) == 60) {
    minutes += 1
    seconds = 0
}
```

## Easier solution
 
I don't know how the Duration object works but I suspect just changing

```
  let { hours = 0, minutes = 0, seconds = 0 } = duration.shiftTo('hours', 'minutes', 'seconds').toObject()
```

to

```
  let { hours = 0, minutes = 0, seconds = 0, milliseconds = 0 } = duration.shiftTo('hours', 'minutes', 'seconds', 'milliseconds').toObject()
```

might fix the problem, since then you don't have to deal with the rounding yourself.

**Comment by Qazzquimby** [comment]
Thanks for the report! To be honest I'm pleased to have a user, since I don't do much marketing. I had trouble reproducing the bad display, but I implemented the `duration.shiftTo` solution which looks sensible.

**Comment by moyamo** [comment]
Awesome, I reproduced the issue using the cached (broken) version, and then refreshed the page and now it is working! Thank you very much.

> To be honest I'm pleased to have a user, since I don't do much marketing

I found your app in the lesswrong comment section.
